[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
escrow_anchor = "4feFvLpc3CaHWLsxD954DCL9mjAdSj61jZD85jag8A32"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "./test_manager.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
